version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed!"
      - ls -la build/ # Verify build directory contents

artifacts:
  files:
    - '**/*'
  base-directory: 'build' # Must match vite.config.js build.outDir